name: Deploy to Fox-net Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy as root user
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        port: 22
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "Starting deployment as root..."
          cd /var/www/FOXNET/
          git pull origin main
          npm install
          pm2 restart server
          systemctl restart nginx
          echo "--- DEBUGGING INFO ---"
          echo "Current directory:"
          pwd
          echo "
File list:"
          ls -la
          echo "
Node version:"
          node -v
          echo "
npm version:"
          npm -v
          echo "
pm2 list:"
          pm2 list
          echo "
Nginx config:"
          cat /etc/nginx/sites-available/default || true
          echo "
Nginx error log:"
          tail -n 50 /var/log/nginx/error.log || true
          echo "
pm2 error log:"
          tail -n 50 ~/.pm2/logs/server-error.log || true
          echo "--- END DEBUGGING INFO ---"
          echo "Deployment completed successfully!"
