name: Deploy to Reg.ru Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Check server availability
      run: |
        echo "Проверяем доступность сервера ${{ secrets.SERVER_IP }}..."
        ping -c 3 ${{ secrets.SERVER_IP }} || echo "Сервер не отвечает на ping"
        nc -zv -w 5 ${{ secrets.SERVER_IP }} 22 && echo "Порт 22 открыт" || echo "Порт 22 недоступен"

    - name: Deploy to Server
      run: |
        echo "🚀 Подключаемся к серверу..."
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -T root@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/fox-net.site/
          git pull origin main
          sudo systemctl restart nginx
          echo "✅ Деплой завершен успешно!"
        EOF
