
name: Test Connection

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test SSH password
      run: |
        sudo apt-get install -y sshpass
        timeout 10s \
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          root@89.111.155.196 "echo 'Success!'" \
          && echo "✅ Connection works!" \
          || echo "❌ Connection failed"
