name: Deploy reg.ru
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.SERVER_IP }}
    username: root
    password: ${{ secrets.SERVER_PASSWORD }}  # ← используем пароль вместо ключа
    script: |
      cd /var/www/fox-net.site/
      git pull origin main
      sudo systemctl restart nginx
