name: Deploy to Reg.ru Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      uses: fifsky/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        user: root
        password: ${{ secrets.SERVER_PASSWORD }}
        command: |
          echo "🚀 Подключаемся к серверу..."
          cd /var/www/fox-net.site/
          git pull origin main
          sudo systemctl restart nginx
          echo "✅ Деплой завершен успешно!"
