name: Deploy to Fox-net Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy as root user
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        port: 22
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "Deploying new version with ecosystem file..."
          cd /var/www/FOXNET/
          git pull origin main
          npm install
          # Delete the old process definition, ignore error if it doesn't exist
          pm2 delete my-fresh-app || true
          # Start the application using the ecosystem file
          pm2 start ecosystem.config.js
          echo "Restarting Nginx..."
          systemctl restart nginx
          echo "Deployment complete!"
