name: Deploy to Fox-net Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy as root user
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        port: 22
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "Starting deployment as root..."
          cd /var/www/FOXNET/
          git pull origin main
          echo ${{ github.sha }} > deployment_sha.txt
          npm install
          npm install pm2 -g
          pm2 restart server.js || pm2 start server.js
          systemctl restart nginx
          echo "Deployment completed successfully!"
