name: Simple Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Copy files
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          scp -r -o StrictHostKeyChecking=no \
          ./* root@89.111.155.196:/var/www/fox-net.site/

    - name: Fix permissions
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          root@89.111.155.196 "
            chown -R www-data:www-data /var/www/fox-net.site/
            chmod -R 755 /var/www/fox-net.site/
            systemctl reload nginx
          "
