name: Deploy to Reg.ru Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: u3236417
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /var/www/u3236417/data/www/fox-net.site
          git pull origin main
          echo "Deployment completed successfully!"
