name: Deploy to Reg.ru Server

on:
  push:
    branches: [ main ] # Запускайте деплой только при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/fox-net.site/
          git pull origin main
          # Дополнительные команды, если нужны (например, перезапуск сервисов)
          sudo systemctl restart nginx
