name: Deploy to VPS on reg.ru

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy files
      run: |
        # Копируем файлы на сервер
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          scp -o StrictHostKeyChecking=no -r \
          ./* root@89.111.155.196:/var/www/fox-net.site/

    - name: Set permissions
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          root@89.111.155.196 "
            chown -R www-data:www-data /var/www/fox-net.site/
            chmod -R 755 /var/www/fox-net.site/
            systemctl reload nginx
            echo '✅ Deployment completed!'
          "
