- name: Deploy to Server
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.SERVER_IP }}
    port: 22  # ← добавляем явное указание порта
    username: root
    password: ${{ secrets.SERVER_PASSWORD }}
    script: |
      echo "🚀 Подключаемся к серверу..."
      cd /var/www/fox-net.site/
      git pull origin main
      sudo systemctl restart nginx
      echo "✅ Деплой завершен успешно!"
