name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy with SCP (no SSH keyscan)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Пропускаем проверку хоста
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* root@89.111.155.196:/var/www/fox-net.site/
