name: Deploy to Reg.ru Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to Server
      run: |
        echo "🚀 Подключаемся к ${{ secrets.SERVER_IP }}..."
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 root@${{ secrets.SERVER_IP }} << 'EOF'
          cd /var/www/fox-net.site/
          git pull origin main
          sudo systemctl restart nginx
          echo "✅ Деплой завершен успешно!"
        EOF
