name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug - Check secret
      run: |
        echo "Password length: ${#SSH_PASSWORD}"
        echo "First 2 chars: ${SSH_PASSWORD:0:2}..."

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Test connection with debug
      run: |
        # Проверим что пароль передается
        echo "Testing with password: ${{ secrets.SSH_PASSWORD }}"
        
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no -v \
          root@89.111.155.196 "echo 'Connection successful'" \
          && echo "✅ SSH works!" \
          || echo "❌ SSH failed"
